export const classes = {
  "Warrior": [
    "Arms",
    "Fury",
    "Protection",
  ],
  "Priest": [
    "Discipline",
    "Holy",
    "Shadow",
  ],
  "Mage": [
    "Arcane",
    "Fire",
    "Frost",
  ],
  "Rogue": [
    "Assassination",
    "Combat",
    "Subtlety",
  ],
  "Druid": [
    "Balance",
    "Feral Combat",
    "Restoration",
  ],
  "Paladin": [
    "Holy",
    "Protection",
    "Retribution",
  ],
  "Shaman": [
    "Elemental",
    "Enhancement",
    "Restoration",
  ],
  "Warlock": [
    "Affliction",
    "Demonology",
    "Destruction",
  ],
  "Hunter": [
    "Beast Mastery",
    "Marksmanship",
    "Survival",
  ],
};

export const classIcons = {
  "Warrior": "class_warrior.png",
  "WarriorArms": "ability_rogue_eviscerate.png",
  "WarriorFury": "ability_warrior_innerrage.png",
  "WarriorProtection": "inv_shield_06.png",
  "Paladin": "class_paladin.png",
  "PaladinHoly": "spell_holy_holybolt.png",
  "PaladinProtection": "spell_holy_devotionaura.png",
  "PaladinRetribution": "spell_holy_auraoflight.png",
  "Hunter": "class_hunter.png",
  "HunterBeastMastery": "ability_hunter_beasttaming.png",
  "HunterMarksmanship": "ability_marksmanship.png",
  "HunterSurvival": "ability_hunter_swiftstrike.png",
  "Rogue": "class_rogue.png",
  "RogueAssassination": "ability_rogue_eviscerate.png",
  "RogueCombat": "ability_backstab.png",
  "RogueSubtlety": "ability_stealth.png",
  "Priest": "class_priest.png",
  "PriestDiscipline": "spell_holy_wordfortitude.png",
  "PriestHoly": "spell_holy_holybolt.png",
  "PriestShadow": "spell_shadow_shadowwordpain.png",
  "Shaman": "class_shaman.png",
  "ShamanElemental": "spell_nature_lightning.png",
  "ShamanEnhancement": "spell_nature_lightningshield.png",
  "ShamanRestoration": "spell_nature_magicimmunity.png",
  "Mage": "class_mage.png",
  "MageArcane": "spell_holy_magicalsentry.png",
  "MageFire": "spell_fire_flamebolt.png",
  "MageFrost": "spell_frost_frostbolt02.png",
  "Warlock": "class_warlock.png",
  "WarlockAffliction": "spell_shadow_deathcoil.png",
  "WarlockDemonology": "spell_shadow_metamorphosis.png",
  "WarlockDestruction": "spell_shadow_rainoffire.png",
  "Druid": "class_druid.png",
  "DruidBalance": "spell_nature_starfall.png",
  "DruidFeralCombat": "ability_racial_bearform.png",
  "DruidRestoration": "spell_nature_healingtouch.png",
};
